# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from cv2 import VideoCapture
import device
from PyQt5.QtGui import QImage
import cv2
import imutils
import numpy as np
import time

# device_list = ["-"*20]
device_list = device.getDeviceList()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):


        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(931, 691)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 100, 500, 300))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setIconSize(QtCore.QSize(50,50))
        # self.pushButton.setGeometry(QtCore.QRect(100, 100, 1, 1))
        self.pushButton.setIcon(QtGui.QIcon("assets/off.png"))	
        self.horizontalLayout.addWidget(self.pushButton)

        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)

        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        for item in device_list:
            self.comboBox.addItem(str(item))
        self.horizontalLayout.addWidget(self.comboBox)

        self.fpsLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fpsLabel.setObjectName("fpsLabel")
        self.horizontalLayout.addWidget(self.fpsLabel)


        self.verticalLayout.addLayout(self.horizontalLayout)
        # self.graphicsView = QtWidgets.QGraphicsView(self.verticalLayoutWidget)
        # self.graphicsView.setObjectName("graphicsView")
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setText("")
        self.imageLabel.setPixmap(QtGui.QPixmap("assets/cam_off.png"))
        self.imageLabel.setObjectName("imageLabel")
        self.imageLabel.setGeometry(QtCore.QRect(0, 0, 700, 21))
        # self.verticalLayout.addWidget(self.graphicsView)
        self.verticalLayout.addWidget(self.imageLabel)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 931, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuHep = QtWidgets.QMenu(self.menubar)
        self.menuHep.setObjectName("menuHep")
        self.menuSettinga = QtWidgets.QMenu(self.menubar)
        self.menuSettinga.setObjectName("menuSettinga")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuSettinga.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuHep.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.comboBox.currentIndexChanged.connect(self.changeIndex)
        self.pushButton.clicked.connect(self.setCamera)


        self.started = False
        self.cap = VideoCapture(0)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Camera"))
        self.menuHelp.setTitle(_translate("MainWindow", "About"))
        self.menuHep.setTitle(_translate("MainWindow", "Hep"))
        self.fpsLabel.setText(_translate("MainWindow", "FPS"))
        self.menuSettinga.setTitle(_translate("MainWindow", "Settings"))

    def changeIndex(self, value):
        self.cap.release()
        self.cap = cv2.VideoCapture(value)

    def setCamera(self):

        cnt, st = 0, 0
        frames_to_count=20
        self.fps=0

        if self.started:
            self.started=False
            # self.pushButton.setText('Start')
            self.pushButton.setIcon(QtGui.QIcon("assets/off.png"))	
        else:
            self.started=True
            # self.pushButton.setText('Stop')
            self.pushButton.setIcon(QtGui.QIcon("assets/on.png"))	

        # print("changed", value)

        while (self.cap.isOpened()):
            QtWidgets.QApplication.processEvents()	
            ret, self.image = self.cap.read()
            self.image  = imutils.resize(self.image ,height = 480)
            if cnt == frames_to_count:
                try: # To avoid divide by 0 we put it in try except
                    self.fps = round(frames_to_count/(time.time()-st)) 
                    st = time.time()
                    cnt=0
                except:
                    pass
            cnt+=1
			
            self.setPhoto(self.image)
            self.update()


            key = cv2.waitKey(1) & 0xFF
            if not self.started:
                self.imageLabel.setPixmap(QtGui.QPixmap("assets/cam_off.png"))
                break

    def setPhoto(self, image):
        self.tmp = image
        frame = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = QImage(frame, frame.shape[1],frame.shape[0],frame.strides[0],QImage.Format_RGB888)
        self.imageLabel.setPixmap(QtGui.QPixmap.fromImage(image))


    def update(self):
        fps = f"FPS: {str(self.fps)}"
        self.fpsLabel.setText(fps)
        # self.setPhoto()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())